/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./supabase-schemas";
export type PublicChallengeStatus = z.infer<
  typeof generated.publicChallengeStatusSchema
>;
export type PublicDraftType = z.infer<typeof generated.publicDraftTypeSchema>;
export type PublicMatchRole = z.infer<typeof generated.publicMatchRoleSchema>;
export type PublicMatchStatus = z.infer<
  typeof generated.publicMatchStatusSchema
>;
export type PublicMatchType = z.infer<typeof generated.publicMatchTypeSchema>;
export type Json = z.infer<typeof generated.jsonSchema>;
export type AdminrolesRow = z.infer<typeof generated.adminRolesRowSchema>;
export type AdminrolesInsert = z.infer<typeof generated.adminRolesInsertSchema>;
export type AdminrolesUpdate = z.infer<typeof generated.adminRolesUpdateSchema>;
export type AdminrolesRelationships = z.infer<
  typeof generated.adminRolesRelationshipsSchema
>;
export type ChallengeteamsRow = z.infer<
  typeof generated.challengeTeamsRowSchema
>;
export type ChallengeteamsInsert = z.infer<
  typeof generated.challengeTeamsInsertSchema
>;
export type ChallengeteamsUpdate = z.infer<
  typeof generated.challengeTeamsUpdateSchema
>;
export type ChallengeteamsRelationships = z.infer<
  typeof generated.challengeTeamsRelationshipsSchema
>;
export type ChallengesRow = z.infer<typeof generated.challengesRowSchema>;
export type ChallengesInsert = z.infer<typeof generated.challengesInsertSchema>;
export type ChallengesUpdate = z.infer<typeof generated.challengesUpdateSchema>;
export type ChallengesRelationships = z.infer<
  typeof generated.challengesRelationshipsSchema
>;
export type EventmatchesRow = z.infer<typeof generated.eventMatchesRowSchema>;
export type EventmatchesInsert = z.infer<
  typeof generated.eventMatchesInsertSchema
>;
export type EventmatchesUpdate = z.infer<
  typeof generated.eventMatchesUpdateSchema
>;
export type EventmatchesRelationships = z.infer<
  typeof generated.eventMatchesRelationshipsSchema
>;
export type EventroundsRow = z.infer<typeof generated.eventRoundsRowSchema>;
export type EventroundsInsert = z.infer<
  typeof generated.eventRoundsInsertSchema
>;
export type EventroundsUpdate = z.infer<
  typeof generated.eventRoundsUpdateSchema
>;
export type EventroundsRelationships = z.infer<
  typeof generated.eventRoundsRelationshipsSchema
>;
export type EventteamsRow = z.infer<typeof generated.eventTeamsRowSchema>;
export type EventteamsInsert = z.infer<typeof generated.eventTeamsInsertSchema>;
export type EventteamsUpdate = z.infer<typeof generated.eventTeamsUpdateSchema>;
export type EventteamsRelationships = z.infer<
  typeof generated.eventTeamsRelationshipsSchema
>;
export type EventsRow = z.infer<typeof generated.eventsRowSchema>;
export type EventsInsert = z.infer<typeof generated.eventsInsertSchema>;
export type EventsUpdate = z.infer<typeof generated.eventsUpdateSchema>;
export type EventsRelationships = z.infer<
  typeof generated.eventsRelationshipsSchema
>;
export type GeneratedserversRow = z.infer<
  typeof generated.generatedServersRowSchema
>;
export type GeneratedserversInsert = z.infer<
  typeof generated.generatedServersInsertSchema
>;
export type GeneratedserversUpdate = z.infer<
  typeof generated.generatedServersUpdateSchema
>;
export type GeneratedserversRelationships = z.infer<
  typeof generated.generatedServersRelationshipsSchema
>;
export type MapsRow = z.infer<typeof generated.mapsRowSchema>;
export type MapsInsert = z.infer<typeof generated.mapsInsertSchema>;
export type MapsUpdate = z.infer<typeof generated.mapsUpdateSchema>;
export type MatchconfigsRow = z.infer<typeof generated.matchConfigsRowSchema>;
export type MatchconfigsInsert = z.infer<
  typeof generated.matchConfigsInsertSchema
>;
export type MatchconfigsUpdate = z.infer<
  typeof generated.matchConfigsUpdateSchema
>;
export type MatchconfigsRelationships = z.infer<
  typeof generated.matchConfigsRelationshipsSchema
>;
export type MatchdraftsRow = z.infer<typeof generated.matchDraftsRowSchema>;
export type MatchdraftsInsert = z.infer<
  typeof generated.matchDraftsInsertSchema
>;
export type MatchdraftsUpdate = z.infer<
  typeof generated.matchDraftsUpdateSchema
>;
export type MatchdraftsRelationships = z.infer<
  typeof generated.matchDraftsRelationshipsSchema
>;
export type MatchmapsRow = z.infer<typeof generated.matchMapsRowSchema>;
export type MatchmapsInsert = z.infer<typeof generated.matchMapsInsertSchema>;
export type MatchmapsUpdate = z.infer<typeof generated.matchMapsUpdateSchema>;
export type MatchmapsRelationships = z.infer<
  typeof generated.matchMapsRelationshipsSchema
>;
export type MatchplayerresultsRow = z.infer<
  typeof generated.matchPlayerResultsRowSchema
>;
export type MatchplayerresultsInsert = z.infer<
  typeof generated.matchPlayerResultsInsertSchema
>;
export type MatchplayerresultsUpdate = z.infer<
  typeof generated.matchPlayerResultsUpdateSchema
>;
export type MatchplayerresultsRelationships = z.infer<
  typeof generated.matchPlayerResultsRelationshipsSchema
>;
export type MatchplayersRow = z.infer<typeof generated.matchPlayersRowSchema>;
export type MatchplayersInsert = z.infer<
  typeof generated.matchPlayersInsertSchema
>;
export type MatchplayersUpdate = z.infer<
  typeof generated.matchPlayersUpdateSchema
>;
export type MatchplayersRelationships = z.infer<
  typeof generated.matchPlayersRelationshipsSchema
>;
export type MatchresultsRow = z.infer<typeof generated.matchResultsRowSchema>;
export type MatchresultsInsert = z.infer<
  typeof generated.matchResultsInsertSchema
>;
export type MatchresultsUpdate = z.infer<
  typeof generated.matchResultsUpdateSchema
>;
export type MatchresultsRelationships = z.infer<
  typeof generated.matchResultsRelationshipsSchema
>;
export type MatchrolesRow = z.infer<typeof generated.matchRolesRowSchema>;
export type MatchrolesInsert = z.infer<typeof generated.matchRolesInsertSchema>;
export type MatchrolesUpdate = z.infer<typeof generated.matchRolesUpdateSchema>;
export type MatchrolesRelationships = z.infer<
  typeof generated.matchRolesRelationshipsSchema
>;
export type MatchserversRow = z.infer<typeof generated.matchServersRowSchema>;
export type MatchserversInsert = z.infer<
  typeof generated.matchServersInsertSchema
>;
export type MatchserversUpdate = z.infer<
  typeof generated.matchServersUpdateSchema
>;
export type MatchserversRelationships = z.infer<
  typeof generated.matchServersRelationshipsSchema
>;
export type MatchesRow = z.infer<typeof generated.matchesRowSchema>;
export type MatchesInsert = z.infer<typeof generated.matchesInsertSchema>;
export type MatchesUpdate = z.infer<typeof generated.matchesUpdateSchema>;
export type MatchesRelationships = z.infer<
  typeof generated.matchesRelationshipsSchema
>;
export type PlayerratingsRow = z.infer<typeof generated.playerRatingsRowSchema>;
export type PlayerratingsInsert = z.infer<
  typeof generated.playerRatingsInsertSchema
>;
export type PlayerratingsUpdate = z.infer<
  typeof generated.playerRatingsUpdateSchema
>;
export type PlayerratingsRelationships = z.infer<
  typeof generated.playerRatingsRelationshipsSchema
>;
export type PlayersRow = z.infer<typeof generated.playersRowSchema>;
export type PlayersInsert = z.infer<typeof generated.playersInsertSchema>;
export type PlayersUpdate = z.infer<typeof generated.playersUpdateSchema>;
export type PlayersduplicateRow = z.infer<
  typeof generated.playersDuplicateRowSchema
>;
export type PlayersduplicateInsert = z.infer<
  typeof generated.playersDuplicateInsertSchema
>;
export type PlayersduplicateUpdate = z.infer<
  typeof generated.playersDuplicateUpdateSchema
>;
export type RoundsRow = z.infer<typeof generated.roundsRowSchema>;
export type RoundsInsert = z.infer<typeof generated.roundsInsertSchema>;
export type RoundsUpdate = z.infer<typeof generated.roundsUpdateSchema>;
export type RoundsRelationships = z.infer<
  typeof generated.roundsRelationshipsSchema
>;
export type ServerrconsRow = z.infer<typeof generated.serverRconsRowSchema>;
export type ServerrconsInsert = z.infer<
  typeof generated.serverRconsInsertSchema
>;
export type ServerrconsUpdate = z.infer<
  typeof generated.serverRconsUpdateSchema
>;
export type ServerrconsRelationships = z.infer<
  typeof generated.serverRconsRelationshipsSchema
>;
export type ServersRow = z.infer<typeof generated.serversRowSchema>;
export type ServersInsert = z.infer<typeof generated.serversInsertSchema>;
export type ServersUpdate = z.infer<typeof generated.serversUpdateSchema>;
export type TeamplayersRow = z.infer<typeof generated.teamPlayersRowSchema>;
export type TeamplayersInsert = z.infer<
  typeof generated.teamPlayersInsertSchema
>;
export type TeamplayersUpdate = z.infer<
  typeof generated.teamPlayersUpdateSchema
>;
export type TeamplayersRelationships = z.infer<
  typeof generated.teamPlayersRelationshipsSchema
>;
export type TeamsRow = z.infer<typeof generated.teamsRowSchema>;
export type TeamsInsert = z.infer<typeof generated.teamsInsertSchema>;
export type TeamsUpdate = z.infer<typeof generated.teamsUpdateSchema>;
export type TeamsRelationships = z.infer<
  typeof generated.teamsRelationshipsSchema
>;
export type TestmatchedclientsRow = z.infer<
  typeof generated.testMatchedClientsRowSchema
>;
export type TestmatchedclientsInsert = z.infer<
  typeof generated.testMatchedClientsInsertSchema
>;
export type TestmatchedclientsUpdate = z.infer<
  typeof generated.testMatchedClientsUpdateSchema
>;
export type TestmatchedclientsRelationships = z.infer<
  typeof generated.testMatchedClientsRelationshipsSchema
>;
export type Ts3uidclientsimportRow = z.infer<
  typeof generated.ts3UidClientsImportRowSchema
>;
export type Ts3uidclientsimportInsert = z.infer<
  typeof generated.ts3UidClientsImportInsertSchema
>;
export type Ts3uidclientsimportUpdate = z.infer<
  typeof generated.ts3UidClientsImportUpdateSchema
>;
