interface Options {
  RCONPassword: string;
  ServerName: string;
  ServerPassword?: string;
  DemoIndexURL: string;
  DemoDownloadURL: string;
  MaxPlayers: number;
  InfantryOnly: boolean;
}
export function generateProfileXml({
  RCONPassword,
  ServerName,
  ServerPassword,
  DemoIndexURL,
  DemoDownloadURL,
  MaxPlayers,
  InfantryOnly,
}: Options): string {
  const passwordElement = ServerPassword
    ? `<ServerPassword>${ServerPassword}</ServerPassword>`
    : '<ServerPassword/>';

  return `<?xml version="1.0" standalone="yes"?>
<Profile>
  <ServerInfo>
    <ServerInfoID>1</ServerInfoID>
    <GameIP>0.0.0.0</GameIP>
    <GamePort>16567</GamePort>
    <GamespyPort>29900</GamespyPort>
    <RCONIP>0.0.0.0</RCONIP>
    <RCONPort>4711</RCONPort>
    <IsInternet>true</IsInternet>
    <AllowNATNegotiate>false</AllowNATNegotiate>
    <PunkbusterEnabled>false</PunkbusterEnabled>
    <RCONPassword>${RCONPassword}</RCONPassword>
  </ServerInfo>
  <GameInfo>
    <GameInfoID>1</GameInfoID>
    <ServerName>${ServerName}</ServerName>
    ${passwordElement}
    <AllowFreeCam>false</AllowFreeCam>
    <AllowExternalViews>true</AllowExternalViews>
    <AllowNoseCam>true</AllowNoseCam>
    <ShowHitIndicator>true</ShowHitIndicator>
    <DeathCamType>0</DeathCamType>
    <MaxPlayers>${MaxPlayers}</MaxPlayers>
    <PlayersToStart>2</PlayersToStart>
    <StartDelay>30</StartDelay>
    <EndDelay>15</EndDelay>
    <SpawnTime>15</SpawnTime>
    <ManDownTime>15</ManDownTime>
    <TicketRatio>200</TicketRatio>
    <RoundsPerMap>99</RoundsPerMap>
    <TimeLimit>20</TimeLimit>
    <ScoreLimit>0</ScoreLimit>
    <SoldierFF>100</SoldierFF>
    <VehicleFF>100</VehicleFF>
    <SoldierFFSplash>100</SoldierFFSplash>
    <VehicleFFSplash>100</VehicleFFSplash>
    <TKPunishEnabled>false</TKPunishEnabled>
    <TKsToKick>3</TKsToKick>
    <TKPunishByDefault>false</TKPunishByDefault>
    <VotingEnabled>false</VotingEnabled>
    <VoteTime>90</VoteTime>
    <MinPlayersVote>2</MinPlayersVote>
    <RestartMapDelay>30</RestartMapDelay>
    <AutoBalanceEnabled>false</AutoBalanceEnabled>
    <TeamRatioPercent>100</TeamRatioPercent>
    <AutoRecordDemo>true</AutoRecordDemo>
    <DemoIndexURL>${DemoIndexURL}</DemoIndexURL>
    <DemoDownloadURL>${DemoDownloadURL}</DemoDownloadURL>
    <AutoDemoHook>adminutils/demo/rotate_demo.py</AutoDemoHook>
    <AdminScript>modmanager</AdminScript>
    <SponsorText/>
    <SponsorLogoURL/>
    <WelcomeMessage/>
    <BandwidthChoke>0</BandwidthChoke>
    <EndOfRoundDelay>15</EndOfRoundDelay>
    <CommunityLogoURL/>
    <NotEnoughPlayersRestartDelay>15</NotEnoughPlayersRestartDelay>
    <UseGlobalRank>false</UseGlobalRank>
    <UseGlobalUnlocks>false</UseGlobalUnlocks>
    <RadioSpamInterval>6</RadioSpamInterval>
    <RadioMaxSpamFlagCount>6</RadioMaxSpamFlagCount>
    <RadioBlockedDurationTime>30</RadioBlockedDurationTime>
    <DemoQuality>3</DemoQuality>
    <Ranked>false</Ranked>
    <ReservedSlots>0</ReservedSlots>
    <Mod>bf2</Mod>
    <MinesFF>0</MinesFF>
    <ShowTKPunishAnnouncements>0</ShowTKPunishAnnouncements>
    <CustomCommands/>
    <CoopBotCount>16</CoopBotCount>
    <CoopBotRatio>50</CoopBotRatio>
    <CoopBotDifficulty>50</CoopBotDifficulty>
    <VotingEnableTeamOnly>false</VotingEnableTeamOnly>
    <InfantryOnly>${InfantryOnly.toString()}</InfantryOnly>
  </GameInfo>
  <RunningMaps>
    <RunningMapID>1</RunningMapID>
    <Order>0</Order>
    <MapName>strike_at_karkand</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>2</RunningMapID>
    <Order>1</Order>
    <MapName>olesko_keep</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>3</RunningMapID>
    <Order>2</Order>
    <MapName>gulf_of_oman</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>4</RunningMapID>
    <Order>3</Order>
    <MapName>dalian_plant</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>5</RunningMapID>
    <Order>4</Order>
    <MapName>daqing_oilfields</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>6</RunningMapID>
    <Order>5</Order>
    <MapName>dragon_valley</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>7</RunningMapID>
    <Order>6</Order>
    <MapName>fushe_pass</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>8</RunningMapID>
    <Order>7</Order>
    <MapName>highway_tampa</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>9</RunningMapID>
    <Order>8</Order>
    <MapName>kubra_dam</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>10</RunningMapID>
    <Order>9</Order>
    <MapName>mashtuur_city</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>11</RunningMapID>
    <Order>10</Order>
    <MapName>midnight_sun</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>12</RunningMapID>
    <Order>11</Order>
    <MapName>operation_blue_pearl</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>13</RunningMapID>
    <Order>12</Order>
    <MapName>operation_clean_sweep</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>14</RunningMapID>
    <Order>13</Order>
    <MapName>operationharvest</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>15</RunningMapID>
    <Order>14</Order>
    <MapName>operationroadrage</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>16</RunningMapID>
    <Order>15</Order>
    <MapName>operationsmokescreen</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>17</RunningMapID>
    <Order>16</Order>
    <MapName>road_to_jalalabad</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>18</RunningMapID>
    <Order>17</Order>
    <MapName>sharqi_peninsula</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>19</RunningMapID>
    <Order>18</Order>
    <MapName>songhua_stalemate</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>20</RunningMapID>
    <Order>19</Order>
    <MapName>taraba_quarry</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>21</RunningMapID>
    <Order>20</Order>
    <MapName>wake_island_2007</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>22</RunningMapID>
    <Order>21</Order>
    <MapName>zatar_wetlands</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>23</RunningMapID>
    <Order>22</Order>
    <MapName>greatwall</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>24</RunningMapID>
    <Order>23</Order>
    <MapName>twl_inf_east_side</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>25</RunningMapID>
    <Order>24</Order>
    <MapName>karkandfu</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>26</RunningMapID>
    <Order>25</Order>
    <MapName>jungle_stream</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>27</RunningMapID>
    <Order>26</Order>
    <MapName>hue</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>28</RunningMapID>
    <Order>27</Order>
    <MapName>goods_station</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>29</RunningMapID>
    <Order>28</Order>
    <MapName>frostbite_night</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>30</RunningMapID>
    <Order>29</Order>
    <MapName>dines_city</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>31</RunningMapID>
    <Order>30</Order>
    <MapName>city_park</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>32</RunningMapID>
    <Order>31</Order>
    <MapName>sharqi_west</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>33</RunningMapID>
    <Order>32</Order>
    <MapName>city_of_the_dead</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>34</RunningMapID>
    <Order>33</Order>
    <MapName>basrah_streets</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>35</RunningMapID>
    <Order>34</Order>
    <MapName>aces_high</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>36</RunningMapID>
    <Order>35</Order>
    <MapName>anctoville_1944</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>37</RunningMapID>
    <Order>36</Order>
    <MapName>de_dust2</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>38</RunningMapID>
    <Order>37</Order>
    <MapName>jungle_city</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>39</RunningMapID>
    <Order>38</Order>
    <MapName>opk_code_bravo</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>40</RunningMapID>
    <Order>39</Order>
    <MapName>opk_village</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>41</RunningMapID>
    <Order>40</Order>
    <MapName>the_battle_for_sfakia</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>42</RunningMapID>
    <Order>41</Order>
    <MapName>tunis_1943</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>43</RunningMapID>
    <Order>42</Order>
    <MapName>street</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>44</RunningMapID>
    <Order>43</Order>
    <MapName>waterfront</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>45</RunningMapID>
    <Order>44</Order>
    <MapName>alcazar</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>46</RunningMapID>
    <Order>45</Order>
    <MapName>street</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <RunningMaps>
    <RunningMapID>47</RunningMapID>
    <Order>46</Order>
    <MapName>waterfront</MapName>
    <GameMode>gpm_cq</GameMode>
    <MaxPlayers>16</MaxPlayers>
  </RunningMaps>
  <VOIPInfo>
    <VOIPInfoID>1</VOIPInfoID>
    <IsRemote>false</IsRemote>
    <ServerRemoteIP/>
    <ServerPort>55125</ServerPort>
    <BFClientPort>55123</BFClientPort>
    <BFServerPort>55124</BFServerPort>
    <SharedPassword/>
    <Quality>3</Quality>
    <IsEnabled>true</IsEnabled>
  </VOIPInfo>
  <ScoreInfo>
    <ScoreInfoID>1</ScoreInfoID>
    <Death>0</Death>
    <Kill>2</Kill>
    <AssistKill>1</AssistKill>
    <InDirectKill>1</InDirectKill>
    <Tk>-4</Tk>
    <Heal>1</Heal>
    <SoldierRevive>2</SoldierRevive>
    <Repair>1</Repair>
    <VehicleRevive>2</VehicleRevive>
    <Ammo>1</Ammo>
    <FlagCapture>5</FlagCapture>
    <FlagReturn>2</FlagReturn>
    <ControlPointCapture>4</ControlPointCapture>
    <Objective>5</Objective>
    <DriverPassenger>1</DriverPassenger>
    <TeamDamage>-1</TeamDamage>
    <TeamVehicleDamage>-2</TeamVehicleDamage>
    <HealScoreLimit>100</HealScoreLimit>
    <RepairScoreLimit>100</RepairScoreLimit>
    <AmmoScoreLimit>100</AmmoScoreLimit>
    <TeamDamageLimit>50</TeamDamageLimit>
    <TeamVehicleDamageLimit>25</TeamVehicleDamageLimit>
  </ScoreInfo>
</Profile>`;
}
