[build]
builder = "nixpacks"
buildCommand = "npm run build -w api"
watchPatterns = ["apps/api", "packages"]
providers = ["node"]

[deploy]
startCommand = "NPM_CONFIG_LOGLEVEL=verbose npm run start -w api"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
